### ISSUE TITLE
Failed to initialize SiteSync

### ISSUE THREAD

**Issue by tanh609** [ynput/ayon-sitesync#36]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

Hello, 

When I first start up our AYON server instance, I encountered the following issue. Please advise.

```
2024-09-16 13:52:49 ERROR      server          Failed to initialize addon /addons/sitesync/1.1.2

    Traceback (most recent call last):
      File "/backend/ayon_server/addons/definition.py", line 84, in versions
        self.init_addon(version_dir)
      File "/backend/ayon_server/addons/definition.py", line 148, in init_addon
        module = import_module(vname, server_module_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/backend/ayon_server/addons/utils.py", line 18, in import_module
        spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 940, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/addons/sitesync/1.1.2/server/__init__.py", line 10, in <module>
        from ayon_server.api import (
    ImportError: cannot import name 'dep_current_user' from 'ayon_server.api' (/backend/ayon_server/api/__init__.py)
```
    
    

### Version

1.0.0

### What platform you are running on?

Windows, Linux / Ubuntu

### Steps To Reproduce:

Our server have all the original codes.

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

**Comment by kalisp** [comment]
This will be sorted out with new release which should be available on the market hopefully today.
Or you could checkout develop, run `create_package.py` and upload created zip from `ADDON_REPO/package` manually in `Studio Settings > Bundles > Upload Addons` (restart server and adding newly installed addon to production bundle)
![image](https://github.com/user-attachments/assets/9ce6d21a-2526-4674-9eec-513706614f64)

**Comment by tanh609** [comment]
Thank you very much @kalisp. I have downloaded the newer version of sitesync from the Addon Market.
